" Pathogen Config
call pathogen#incubate()
call pathogen#helptags()

" General
set hidden
set vb t_vb=
set ts=2 sts=2 sw=2 expandtab

" Display
set number
set ruler
set cursorline
set list
set listchars=tab:\ \
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<

" Color Scheme
syntax on
colorscheme jellybeans

" NERDTree mapping
let NERDTreeShowHidden=1
map <Leader>nt :NERDTree <cr>
let NERDTreeShowLineNumbers=1

" JSHint
let g:syntastic_javascript_checker='jshint'

" Strip trailing whitespace (,ss)
function! StripWhitespace ()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    :%s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfunction
noremap <leader>ss :call StripWhitespace ()<CR>
